version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  producer:
    build: 
      context: ./producer
      dockerfile: Dockerfile.producer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=password
    restart: always

  text_agent:
    build: 
      context: ./agents
      dockerfile: Dockerfile.text
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=password
      - HF_TOKEN= #Añadir token propio READ de Hugging Face #
    volumes:
      - ./results:/results
    restart: always

  image_agent:
    build:
      context: ./agents  
      dockerfile: Dockerfile.image    
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=password
      - HF_TOKEN=  #Añadir token propio READ de Hugging Face #
    volumes:
      - ./results:/results
    restart: always
volumes:
  rabbitmq_data: