FROM python:3.9-slim
WORKDIR /app
RUN pip install \
    pika==1.3.2 \
    tensorflow==2.12.0 \
    tensorflow-addons==0.20.0 \
    numpy \
    "huggingface_hub==0.16.4"
COPY image_agent.py .
CMD ["python","-u","image_agent.py"]